namespace {NAMESPACE_PLACEHOLDER};

struct Waypoint {
    identifier: uint;
    latitude: double;
    longitude: double;
}

table SimulatorMetadata {
    // The timestamp of the image frame in microseconds
    timestamp: ulong;

    // The sequence number of the image frame
    sequence_number: uint;

    // The identifier for the map used in the simulation environment
    map_id: string;

    // The latitudinal and longitudinal lenghts for meter conversion
    latitude_length: double;
    longitude_length: double;

    // The set of available waypoints in the simulation environment
    waypoints: [Waypoint];
}

root_type SimulatorMetadata;