// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AudibleFeedback : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AudibleFeedback GetRootAsAudibleFeedback(ByteBuffer _bb) { return GetRootAsAudibleFeedback(_bb, new AudibleFeedback()); }
  public static AudibleFeedback GetRootAsAudibleFeedback(ByteBuffer _bb, AudibleFeedback obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyAudibleFeedback(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, AudibleFeedbackVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AudibleFeedback __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Filename { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFilenameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetFilenameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetFilenameArray() { return __p.__vector_as_array<byte>(4); }
  public bool StopAllSounds { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Messages.AudibleFeedback> CreateAudibleFeedback(FlatBufferBuilder builder,
      StringOffset filenameOffset = default(StringOffset),
      bool stop_all_sounds = false) {
    builder.StartTable(2);
    AudibleFeedback.AddFilename(builder, filenameOffset);
    AudibleFeedback.AddStopAllSounds(builder, stop_all_sounds);
    return AudibleFeedback.EndAudibleFeedback(builder);
  }

  public static void StartAudibleFeedback(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddFilename(FlatBufferBuilder builder, StringOffset filenameOffset) { builder.AddOffset(0, filenameOffset.Value, 0); }
  public static void AddStopAllSounds(FlatBufferBuilder builder, bool stopAllSounds) { builder.AddBool(1, stopAllSounds, false); }
  public static Offset<Messages.AudibleFeedback> EndAudibleFeedback(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.AudibleFeedback>(o);
  }
  public static void FinishAudibleFeedbackBuffer(FlatBufferBuilder builder, Offset<Messages.AudibleFeedback> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedAudibleFeedbackBuffer(FlatBufferBuilder builder, Offset<Messages.AudibleFeedback> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class AudibleFeedbackVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Filename*/, false)
      && verifier.VerifyField(tablePos, 6 /*StopAllSounds*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
