// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Lane : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Lane GetRootAsLane(ByteBuffer _bb) { return GetRootAsLane(_bb, new Lane()); }
  public static Lane GetRootAsLane(ByteBuffer _bb, Lane obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyLane(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, LaneVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Lane __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public int Lane_ { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Messages.Lane> CreateLane(FlatBufferBuilder builder,
      ulong timestamp = 0,
      int lane = 0) {
    builder.StartTable(2);
    Lane.AddTimestamp(builder, timestamp);
    Lane.AddLane(builder, lane);
    return Lane.EndLane(builder);
  }

  public static void StartLane(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddLane(FlatBufferBuilder builder, int lane) { builder.AddInt(1, lane, 0); }
  public static Offset<Messages.Lane> EndLane(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.Lane>(o);
  }
  public static void FinishLaneBuffer(FlatBufferBuilder builder, Offset<Messages.Lane> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedLaneBuffer(FlatBufferBuilder builder, Offset<Messages.Lane> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class LaneVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Lane*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
