// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Orientation {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Orientation {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

pitch():number {
  return this.bb!.readFloat32(this.bb_pos);
}

roll():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

yaw():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

static sizeOf():number {
  return 12;
}

static createOrientation(builder:flatbuffers.Builder, pitch: number, roll: number, yaw: number):flatbuffers.Offset {
  builder.prep(4, 12);
  builder.writeFloat32(yaw);
  builder.writeFloat32(roll);
  builder.writeFloat32(pitch);
  return builder.offset();
}

}
