// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Location } from '../flatbuffers/location.js';
import { Orientation } from '../flatbuffers/orientation.js';


export class VectornavReport {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VectornavReport {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVectornavReport(bb:flatbuffers.ByteBuffer, obj?:VectornavReport):VectornavReport {
  return (obj || new VectornavReport()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVectornavReport(bb:flatbuffers.ByteBuffer, obj?:VectornavReport):VectornavReport {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VectornavReport()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

sequenceNumber():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

location(obj?:Location):Location|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Location()).__init(this.bb_pos + offset, this.bb!) : null;
}

orientation(obj?:Orientation):Orientation|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Orientation()).__init(this.bb_pos + offset, this.bb!) : null;
}

numSatellites():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

fixQuality():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
}

static startVectornavReport(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static addSequenceNumber(builder:flatbuffers.Builder, sequenceNumber:number) {
  builder.addFieldInt32(1, sequenceNumber, 0);
}

static addLocation(builder:flatbuffers.Builder, locationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, locationOffset, 0);
}

static addOrientation(builder:flatbuffers.Builder, orientationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, orientationOffset, 0);
}

static addNumSatellites(builder:flatbuffers.Builder, numSatellites:number) {
  builder.addFieldInt16(4, numSatellites, 0);
}

static addFixQuality(builder:flatbuffers.Builder, fixQuality:number) {
  builder.addFieldInt8(5, fixQuality, 0);
}

static endVectornavReport(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishVectornavReportBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedVectornavReportBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

}
