// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Location {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Location {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

latitude():number {
  return this.bb!.readFloat64(this.bb_pos);
}

longitude():number {
  return this.bb!.readFloat64(this.bb_pos + 8);
}

static sizeOf():number {
  return 16;
}

static createLocation(builder:flatbuffers.Builder, latitude: number, longitude: number):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.writeFloat64(longitude);
  builder.writeFloat64(latitude);
  return builder.offset();
}

}
