// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Waypoint } from '../messages/waypoint.js';


export class SimulatorMetadata {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SimulatorMetadata {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSimulatorMetadata(bb:flatbuffers.ByteBuffer, obj?:SimulatorMetadata):SimulatorMetadata {
  return (obj || new SimulatorMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSimulatorMetadata(bb:flatbuffers.ByteBuffer, obj?:SimulatorMetadata):SimulatorMetadata {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SimulatorMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

sequenceNumber():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

mapId():string|null
mapId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mapId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

latitudeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

longitudeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

waypoints(index: number, obj?:Waypoint):Waypoint|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new Waypoint()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 24, this.bb!) : null;
}

waypointsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSimulatorMetadata(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static addSequenceNumber(builder:flatbuffers.Builder, sequenceNumber:number) {
  builder.addFieldInt32(1, sequenceNumber, 0);
}

static addMapId(builder:flatbuffers.Builder, mapIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, mapIdOffset, 0);
}

static addLatitudeLength(builder:flatbuffers.Builder, latitudeLength:number) {
  builder.addFieldFloat64(3, latitudeLength, 0.0);
}

static addLongitudeLength(builder:flatbuffers.Builder, longitudeLength:number) {
  builder.addFieldFloat64(4, longitudeLength, 0.0);
}

static addWaypoints(builder:flatbuffers.Builder, waypointsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, waypointsOffset, 0);
}

static startWaypointsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(24, numElems, 8);
}

static endSimulatorMetadata(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishSimulatorMetadataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedSimulatorMetadataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createSimulatorMetadata(builder:flatbuffers.Builder, timestamp:bigint, sequenceNumber:number, mapIdOffset:flatbuffers.Offset, latitudeLength:number, longitudeLength:number, waypointsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SimulatorMetadata.startSimulatorMetadata(builder);
  SimulatorMetadata.addTimestamp(builder, timestamp);
  SimulatorMetadata.addSequenceNumber(builder, sequenceNumber);
  SimulatorMetadata.addMapId(builder, mapIdOffset);
  SimulatorMetadata.addLatitudeLength(builder, latitudeLength);
  SimulatorMetadata.addLongitudeLength(builder, longitudeLength);
  SimulatorMetadata.addWaypoints(builder, waypointsOffset);
  return SimulatorMetadata.endSimulatorMetadata(builder);
}
}
