// automatically generated by the FlatBuffers compiler, do not modify

package com.soonerrobotics.flatbuffers.arc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ArcLog extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ArcLog getRootAsArcLog(ByteBuffer _bb) { return getRootAsArcLog(_bb, new ArcLog()); }
  public static ArcLog getRootAsArcLog(ByteBuffer _bb, ArcLog obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ArcLog __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long timestamp() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long sequenceNumber() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String methodCaller() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer methodCallerAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer methodCallerInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String logLevel() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer logLevelAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer logLevelInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String message() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer messageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }

  public static int createArcLog(FlatBufferBuilder builder,
      long timestamp,
      long sequenceNumber,
      int methodCallerOffset,
      int logLevelOffset,
      int messageOffset) {
    builder.startTable(5);
    ArcLog.addTimestamp(builder, timestamp);
    ArcLog.addMessage(builder, messageOffset);
    ArcLog.addLogLevel(builder, logLevelOffset);
    ArcLog.addMethodCaller(builder, methodCallerOffset);
    ArcLog.addSequenceNumber(builder, sequenceNumber);
    return ArcLog.endArcLog(builder);
  }

  public static void startArcLog(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(0, timestamp, 0L); }
  public static void addSequenceNumber(FlatBufferBuilder builder, long sequenceNumber) { builder.addInt(1, (int) sequenceNumber, (int) 0L); }
  public static void addMethodCaller(FlatBufferBuilder builder, int methodCallerOffset) { builder.addOffset(2, methodCallerOffset, 0); }
  public static void addLogLevel(FlatBufferBuilder builder, int logLevelOffset) { builder.addOffset(3, logLevelOffset, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(4, messageOffset, 0); }
  public static int endArcLog(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishArcLogBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedArcLogBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ArcLog get(int j) { return get(new ArcLog(), j); }
    public ArcLog get(ArcLog obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

