// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ArcLog {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ArcLog {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsArcLog(bb:flatbuffers.ByteBuffer, obj?:ArcLog):ArcLog {
  return (obj || new ArcLog()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsArcLog(bb:flatbuffers.ByteBuffer, obj?:ArcLog):ArcLog {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ArcLog()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

sequenceNumber():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

methodCaller():string|null
methodCaller(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
methodCaller(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

logLevel():string|null
logLevel(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
logLevel(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startArcLog(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static addSequenceNumber(builder:flatbuffers.Builder, sequenceNumber:number) {
  builder.addFieldInt32(1, sequenceNumber, 0);
}

static addMethodCaller(builder:flatbuffers.Builder, methodCallerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, methodCallerOffset, 0);
}

static addLogLevel(builder:flatbuffers.Builder, logLevelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, logLevelOffset, 0);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, messageOffset, 0);
}

static endArcLog(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishArcLogBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedArcLogBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createArcLog(builder:flatbuffers.Builder, timestamp:bigint, sequenceNumber:number, methodCallerOffset:flatbuffers.Offset, logLevelOffset:flatbuffers.Offset, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  ArcLog.startArcLog(builder);
  ArcLog.addTimestamp(builder, timestamp);
  ArcLog.addSequenceNumber(builder, sequenceNumber);
  ArcLog.addMethodCaller(builder, methodCallerOffset);
  ArcLog.addLogLevel(builder, logLevelOffset);
  ArcLog.addMessage(builder, messageOffset);
  return ArcLog.endArcLog(builder);
}
}
