// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Arc
{

public enum ArcCommandId : uint
{
  UnknownCommand = 0,
  ToolsStartOpenCvCalibration = 1,
  ToolsStopOpenCvCalibration = 2,
  ToolsSaveOpenCvCalibration = 3,
  ToolsStartHsvCalibration = 4,
  ToolsStopHsvCalibration = 5,
  ToolsEditHsvCalibration = 6,
  ToolsSaveHsvCalibration = 7,
  CurrentSensorInitialize = 256,
  CurrentSensorSetBaudrate = 257,
  CurrentSensorSaveEeprom = 258,
};


}
