// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Arc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ArcData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ArcData GetRootAsArcData(ByteBuffer _bb) { return GetRootAsArcData(_bb, new ArcData()); }
  public static ArcData GetRootAsArcData(ByteBuffer _bb, ArcData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyArcData(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ArcDataVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ArcData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint SequenceNumber { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string DataIdentifier { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataIdentifierBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetDataIdentifierBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetDataIdentifierArray() { return __p.__vector_as_array<byte>(8); }
  public byte DataPayload(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int DataPayloadLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataPayloadBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetDataPayloadBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetDataPayloadArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<Messages.Arc.ArcData> CreateArcData(FlatBufferBuilder builder,
      ulong timestamp = 0,
      uint sequence_number = 0,
      StringOffset data_identifierOffset = default(StringOffset),
      VectorOffset data_payloadOffset = default(VectorOffset)) {
    builder.StartTable(4);
    ArcData.AddTimestamp(builder, timestamp);
    ArcData.AddDataPayload(builder, data_payloadOffset);
    ArcData.AddDataIdentifier(builder, data_identifierOffset);
    ArcData.AddSequenceNumber(builder, sequence_number);
    return ArcData.EndArcData(builder);
  }

  public static void StartArcData(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddSequenceNumber(FlatBufferBuilder builder, uint sequenceNumber) { builder.AddUint(1, sequenceNumber, 0); }
  public static void AddDataIdentifier(FlatBufferBuilder builder, StringOffset dataIdentifierOffset) { builder.AddOffset(2, dataIdentifierOffset.Value, 0); }
  public static void AddDataPayload(FlatBufferBuilder builder, VectorOffset dataPayloadOffset) { builder.AddOffset(3, dataPayloadOffset.Value, 0); }
  public static VectorOffset CreateDataPayloadVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDataPayloadVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataPayloadVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataPayloadVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataPayloadVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<Messages.Arc.ArcData> EndArcData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.Arc.ArcData>(o);
  }
  public static void FinishArcDataBuffer(FlatBufferBuilder builder, Offset<Messages.Arc.ArcData> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedArcDataBuffer(FlatBufferBuilder builder, Offset<Messages.Arc.ArcData> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ArcDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*SequenceNumber*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*DataIdentifier*/, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*DataPayload*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
