namespace {NAMESPACE_PLACEHOLDER}.arc;

enum ArcCommandId : uint {
    // Default
    UnknownCommand = 0x00,

    // OpenCv Calibration
    ToolsStartOpenCvCalibration = 0x01,
    ToolsStopOpenCvCalibration = 0x02,
    ToolsSaveOpenCvCalibration = 0x03,

    // Hsv Calibration
    ToolsStartHsvCalibration = 0x04,
    ToolsStopHsvCalibration = 0x05,
    ToolsEditHsvCalibration = 0x06,
    ToolsSaveHsvCalibration = 0x07,

    // Current Sensor
    CurrentSensorInitialize = 0x100,
    CurrentSensorSetBaudrate = 0x101,
    CurrentSensorSaveEeprom = 0x102,

    GetConfigSnapshot = 0x200,
    SetConfigKey      = 0x201,
    GetPresetList     = 0x202,
    LoadPreset        = 0x203,
    SavePreset        = 0x204,
}

enum ArcCommandPurpose : uint {
    // Default
    UnknownPurpose = 0x00,

    // Standard
    Request = 0x01,
    Response = 0x02,
}

table ArcCommand {
    // The timestamp of the arc command in microseconds
    timestamp: ulong;

    // The sequence number of the arc command
    sequence_number: uint;

    // The purpose of this arc command, 0 = request and 1 = acknowledgment
    purpose: ArcCommandPurpose;

    // The identifier for this command
    command_id: ArcCommandId;

    // The data backing this command
    data: [ubyte];
}

root_type ArcCommand;