// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ArcCapability {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ArcCapability {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsArcCapability(bb:flatbuffers.ByteBuffer, obj?:ArcCapability):ArcCapability {
  return (obj || new ArcCapability()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsArcCapability(bb:flatbuffers.ByteBuffer, obj?:ArcCapability):ArcCapability {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ArcCapability()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

sequenceNumber():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

purpose():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

visionCapabilities():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

telemetryCapabilities():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

miscCapabilities():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startArcCapability(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static addSequenceNumber(builder:flatbuffers.Builder, sequenceNumber:number) {
  builder.addFieldInt32(1, sequenceNumber, 0);
}

static addPurpose(builder:flatbuffers.Builder, purpose:number) {
  builder.addFieldInt32(2, purpose, 0);
}

static addVisionCapabilities(builder:flatbuffers.Builder, visionCapabilities:number) {
  builder.addFieldInt32(3, visionCapabilities, 0);
}

static addTelemetryCapabilities(builder:flatbuffers.Builder, telemetryCapabilities:number) {
  builder.addFieldInt32(4, telemetryCapabilities, 0);
}

static addMiscCapabilities(builder:flatbuffers.Builder, miscCapabilities:number) {
  builder.addFieldInt32(5, miscCapabilities, 0);
}

static endArcCapability(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishArcCapabilityBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedArcCapabilityBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createArcCapability(builder:flatbuffers.Builder, timestamp:bigint, sequenceNumber:number, purpose:number, visionCapabilities:number, telemetryCapabilities:number, miscCapabilities:number):flatbuffers.Offset {
  ArcCapability.startArcCapability(builder);
  ArcCapability.addTimestamp(builder, timestamp);
  ArcCapability.addSequenceNumber(builder, sequenceNumber);
  ArcCapability.addPurpose(builder, purpose);
  ArcCapability.addVisionCapabilities(builder, visionCapabilities);
  ArcCapability.addTelemetryCapabilities(builder, telemetryCapabilities);
  ArcCapability.addMiscCapabilities(builder, miscCapabilities);
  return ArcCapability.endArcCapability(builder);
}
}
