// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ArcHistogram {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ArcHistogram {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsArcHistogram(bb:flatbuffers.ByteBuffer, obj?:ArcHistogram):ArcHistogram {
  return (obj || new ArcHistogram()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsArcHistogram(bb:flatbuffers.ByteBuffer, obj?:ArcHistogram):ArcHistogram {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ArcHistogram()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

sequenceNumber():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

minHue():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

maxHue():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

minSaturation():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

maxSaturation():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

minValue():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

maxValue():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startArcHistogram(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static addSequenceNumber(builder:flatbuffers.Builder, sequenceNumber:number) {
  builder.addFieldInt32(1, sequenceNumber, 0);
}

static addMinHue(builder:flatbuffers.Builder, minHue:number) {
  builder.addFieldFloat32(2, minHue, 0.0);
}

static addMaxHue(builder:flatbuffers.Builder, maxHue:number) {
  builder.addFieldFloat32(3, maxHue, 0.0);
}

static addMinSaturation(builder:flatbuffers.Builder, minSaturation:number) {
  builder.addFieldFloat32(4, minSaturation, 0.0);
}

static addMaxSaturation(builder:flatbuffers.Builder, maxSaturation:number) {
  builder.addFieldFloat32(5, maxSaturation, 0.0);
}

static addMinValue(builder:flatbuffers.Builder, minValue:number) {
  builder.addFieldFloat32(6, minValue, 0.0);
}

static addMaxValue(builder:flatbuffers.Builder, maxValue:number) {
  builder.addFieldFloat32(7, maxValue, 0.0);
}

static endArcHistogram(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishArcHistogramBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedArcHistogramBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createArcHistogram(builder:flatbuffers.Builder, timestamp:bigint, sequenceNumber:number, minHue:number, maxHue:number, minSaturation:number, maxSaturation:number, minValue:number, maxValue:number):flatbuffers.Offset {
  ArcHistogram.startArcHistogram(builder);
  ArcHistogram.addTimestamp(builder, timestamp);
  ArcHistogram.addSequenceNumber(builder, sequenceNumber);
  ArcHistogram.addMinHue(builder, minHue);
  ArcHistogram.addMaxHue(builder, maxHue);
  ArcHistogram.addMinSaturation(builder, minSaturation);
  ArcHistogram.addMaxSaturation(builder, maxSaturation);
  ArcHistogram.addMinValue(builder, minValue);
  ArcHistogram.addMaxValue(builder, maxValue);
  return ArcHistogram.endArcHistogram(builder);
}
}
