// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ArcCommandId } from '../../messages/arc/arc-command-id.js';
import { ArcCommandPurpose } from '../../messages/arc/arc-command-purpose.js';


export class ArcCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ArcCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsArcCommand(bb:flatbuffers.ByteBuffer, obj?:ArcCommand):ArcCommand {
  return (obj || new ArcCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsArcCommand(bb:flatbuffers.ByteBuffer, obj?:ArcCommand):ArcCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ArcCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

sequenceNumber():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

purpose():ArcCommandPurpose {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : ArcCommandPurpose.UnknownPurpose;
}

commandId():ArcCommandId {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : ArcCommandId.UnknownCommand;
}

data(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

dataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

dataArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startArcCommand(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static addSequenceNumber(builder:flatbuffers.Builder, sequenceNumber:number) {
  builder.addFieldInt32(1, sequenceNumber, 0);
}

static addPurpose(builder:flatbuffers.Builder, purpose:ArcCommandPurpose) {
  builder.addFieldInt32(2, purpose, ArcCommandPurpose.UnknownPurpose);
}

static addCommandId(builder:flatbuffers.Builder, commandId:ArcCommandId) {
  builder.addFieldInt32(3, commandId, ArcCommandId.UnknownCommand);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, dataOffset, 0);
}

static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endArcCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishArcCommandBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedArcCommandBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createArcCommand(builder:flatbuffers.Builder, timestamp:bigint, sequenceNumber:number, purpose:ArcCommandPurpose, commandId:ArcCommandId, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  ArcCommand.startArcCommand(builder);
  ArcCommand.addTimestamp(builder, timestamp);
  ArcCommand.addSequenceNumber(builder, sequenceNumber);
  ArcCommand.addPurpose(builder, purpose);
  ArcCommand.addCommandId(builder, commandId);
  ArcCommand.addData(builder, dataOffset);
  return ArcCommand.endArcCommand(builder);
}
}
