// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class AudibleFeedback {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AudibleFeedback {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAudibleFeedback(bb:flatbuffers.ByteBuffer, obj?:AudibleFeedback):AudibleFeedback {
  return (obj || new AudibleFeedback()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAudibleFeedback(bb:flatbuffers.ByteBuffer, obj?:AudibleFeedback):AudibleFeedback {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AudibleFeedback()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

filename():string|null
filename(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
filename(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

stopAllSounds():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startAudibleFeedback(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addFilename(builder:flatbuffers.Builder, filenameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, filenameOffset, 0);
}

static addStopAllSounds(builder:flatbuffers.Builder, stopAllSounds:boolean) {
  builder.addFieldInt8(1, +stopAllSounds, +false);
}

static endAudibleFeedback(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishAudibleFeedbackBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedAudibleFeedbackBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createAudibleFeedback(builder:flatbuffers.Builder, filenameOffset:flatbuffers.Offset, stopAllSounds:boolean):flatbuffers.Offset {
  AudibleFeedback.startAudibleFeedback(builder);
  AudibleFeedback.addFilename(builder, filenameOffset);
  AudibleFeedback.addStopAllSounds(builder, stopAllSounds);
  return AudibleFeedback.endAudibleFeedback(builder);
}
}
