// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class Lane {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Lane {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLane(bb:flatbuffers.ByteBuffer, obj?:Lane):Lane {
  return (obj || new Lane()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLane(bb:flatbuffers.ByteBuffer, obj?:Lane):Lane {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Lane()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

lane():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startLane(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static addLane(builder:flatbuffers.Builder, lane:number) {
  builder.addFieldInt32(1, lane, 0);
}

static endLane(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishLaneBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedLaneBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createLane(builder:flatbuffers.Builder, timestamp:bigint, lane:number):flatbuffers.Offset {
  Lane.startLane(builder);
  Lane.addTimestamp(builder, timestamp);
  Lane.addLane(builder, lane);
  return Lane.endLane(builder);
}
}
