// automatically generated by the FlatBuffers compiler, do not modify
// (config IDs appended manually — keep in sync with C# ArcCommandId enum)
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export enum ArcCommandId {
  UnknownCommand = 0,
  ToolsStartOpenCvCalibration = 1,
  ToolsStopOpenCvCalibration = 2,
  ToolsSaveOpenCvCalibration = 3,
  ToolsStartHsvCalibration = 4,
  ToolsStopHsvCalibration = 5,
  ToolsEditHsvCalibration = 6,
  ToolsSaveHsvCalibration = 7,
  CurrentSensorInitialize = 256,
  CurrentSensorSetBaudrate = 257,
  CurrentSensorSaveEeprom = 258,
  GetConfigSnapshot = 512,
  SetConfigKey = 513,
  GetPresetList = 514,
  LoadPreset = 515,
  SavePreset = 516
}
