// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ArcData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ArcData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsArcData(bb:flatbuffers.ByteBuffer, obj?:ArcData):ArcData {
  return (obj || new ArcData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsArcData(bb:flatbuffers.ByteBuffer, obj?:ArcData):ArcData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ArcData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

sequenceNumber():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

dataIdentifier():string|null
dataIdentifier(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
dataIdentifier(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

dataPayload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

dataPayloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

dataPayloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startArcData(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static addSequenceNumber(builder:flatbuffers.Builder, sequenceNumber:number) {
  builder.addFieldInt32(1, sequenceNumber, 0);
}

static addDataIdentifier(builder:flatbuffers.Builder, dataIdentifierOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, dataIdentifierOffset, 0);
}

static addDataPayload(builder:flatbuffers.Builder, dataPayloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, dataPayloadOffset, 0);
}

static createDataPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startDataPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endArcData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishArcDataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedArcDataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createArcData(builder:flatbuffers.Builder, timestamp:bigint, sequenceNumber:number, dataIdentifierOffset:flatbuffers.Offset, dataPayloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  ArcData.startArcData(builder);
  ArcData.addTimestamp(builder, timestamp);
  ArcData.addSequenceNumber(builder, sequenceNumber);
  ArcData.addDataIdentifier(builder, dataIdentifierOffset);
  ArcData.addDataPayload(builder, dataPayloadOffset);
  return ArcData.endArcData(builder);
}
}
