// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MetricAggregate } from '../../messages/performance/metric-aggregate.js';


export class MetricDefinition {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MetricDefinition {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMetricDefinition(bb:flatbuffers.ByteBuffer, obj?:MetricDefinition):MetricDefinition {
  return (obj || new MetricDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMetricDefinition(bb:flatbuffers.ByteBuffer, obj?:MetricDefinition):MetricDefinition {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MetricDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

subsystem():string|null
subsystem(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
subsystem(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

group():string|null
group(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
group(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

unit():string|null
unit(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
unit(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

aggregate():MetricAggregate {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MetricAggregate.Last;
}

static startMetricDefinition(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addSubsystem(builder:flatbuffers.Builder, subsystemOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, subsystemOffset, 0);
}

static addGroup(builder:flatbuffers.Builder, groupOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, groupOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static addUnit(builder:flatbuffers.Builder, unitOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, unitOffset, 0);
}

static addAggregate(builder:flatbuffers.Builder, aggregate:MetricAggregate) {
  builder.addFieldInt8(4, aggregate, MetricAggregate.Last);
}

static endMetricDefinition(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMetricDefinition(builder:flatbuffers.Builder, subsystemOffset:flatbuffers.Offset, groupOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, unitOffset:flatbuffers.Offset, aggregate:MetricAggregate):flatbuffers.Offset {
  MetricDefinition.startMetricDefinition(builder);
  MetricDefinition.addSubsystem(builder, subsystemOffset);
  MetricDefinition.addGroup(builder, groupOffset);
  MetricDefinition.addName(builder, nameOffset);
  MetricDefinition.addUnit(builder, unitOffset);
  MetricDefinition.addAggregate(builder, aggregate);
  return MetricDefinition.endMetricDefinition(builder);
}
}
