// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Waypoint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Waypoint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

identifier():number {
  return this.bb!.readUint32(this.bb_pos);
}

latitude():number {
  return this.bb!.readFloat64(this.bb_pos + 8);
}

longitude():number {
  return this.bb!.readFloat64(this.bb_pos + 16);
}

static sizeOf():number {
  return 24;
}

static createWaypoint(builder:flatbuffers.Builder, identifier: number, latitude: number, longitude: number):flatbuffers.Offset {
  builder.prep(8, 24);
  builder.writeFloat64(longitude);
  builder.writeFloat64(latitude);
  builder.pad(4);
  builder.writeInt32(identifier);
  return builder.offset();
}

}
