// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ArcCommandId {
  UnknownCommand = 0,
  ToolsStartOpenCvCalibration = 1,
  ToolsStopOpenCvCalibration = 2,
  ToolsSaveOpenCvCalibration = 3,
  ToolsStartHsvCalibration = 4,
  ToolsStopHsvCalibration = 5,
  ToolsEditHsvCalibration = 6,
  ToolsSaveHsvCalibration = 7
}
