// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class PerformanceSample {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PerformanceSample {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPerformanceSample(bb:flatbuffers.ByteBuffer, obj?:PerformanceSample):PerformanceSample {
  return (obj || new PerformanceSample()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPerformanceSample(bb:flatbuffers.ByteBuffer, obj?:PerformanceSample):PerformanceSample {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PerformanceSample()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

subsystem():string|null
subsystem(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
subsystem(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

metric():string|null
metric(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
metric(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

unit():string|null
unit(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
unit(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

timestampMs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startPerformanceSample(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addSubsystem(builder:flatbuffers.Builder, subsystemOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, subsystemOffset, 0);
}

static addMetric(builder:flatbuffers.Builder, metricOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, metricOffset, 0);
}

static addUnit(builder:flatbuffers.Builder, unitOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, unitOffset, 0);
}

static addTimestampMs(builder:flatbuffers.Builder, timestampMs:bigint) {
  builder.addFieldInt64(3, timestampMs, BigInt('0'));
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldFloat64(4, value, 0.0);
}

static endPerformanceSample(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishPerformanceSampleBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedPerformanceSampleBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createPerformanceSample(builder:flatbuffers.Builder, subsystemOffset:flatbuffers.Offset, metricOffset:flatbuffers.Offset, unitOffset:flatbuffers.Offset, timestampMs:bigint, value:number):flatbuffers.Offset {
  PerformanceSample.startPerformanceSample(builder);
  PerformanceSample.addSubsystem(builder, subsystemOffset);
  PerformanceSample.addMetric(builder, metricOffset);
  PerformanceSample.addUnit(builder, unitOffset);
  PerformanceSample.addTimestampMs(builder, timestampMs);
  PerformanceSample.addValue(builder, value);
  return PerformanceSample.endPerformanceSample(builder);
}
}
