// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MetricDefinition } from '../../messages/performance/metric-definition.js';


export class MetricSchema {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MetricSchema {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMetricSchema(bb:flatbuffers.ByteBuffer, obj?:MetricSchema):MetricSchema {
  return (obj || new MetricSchema()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMetricSchema(bb:flatbuffers.ByteBuffer, obj?:MetricSchema):MetricSchema {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MetricSchema()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

metrics(index: number, obj?:MetricDefinition):MetricDefinition|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MetricDefinition()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

metricsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startMetricSchema(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMetrics(builder:flatbuffers.Builder, metricsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, metricsOffset, 0);
}

static createMetricsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMetricsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endMetricSchema(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishMetricSchemaBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedMetricSchemaBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createMetricSchema(builder:flatbuffers.Builder, metricsOffset:flatbuffers.Offset):flatbuffers.Offset {
  MetricSchema.startMetricSchema(builder);
  MetricSchema.addMetrics(builder, metricsOffset);
  return MetricSchema.endMetricSchema(builder);
}
}
