// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MetricAggregate {
  Last = 0,
  Average = 1,
  Min = 2,
  Max = 3
}
