// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MetricAggregate } from '../../messages/performance/metric-aggregate.js';


export class MetricSample {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MetricSample {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMetricSample(bb:flatbuffers.ByteBuffer, obj?:MetricSample):MetricSample {
  return (obj || new MetricSample()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMetricSample(bb:flatbuffers.ByteBuffer, obj?:MetricSample):MetricSample {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MetricSample()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

subsystem():string|null
subsystem(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
subsystem(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

group():string|null
group(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
group(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

unit():string|null
unit(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
unit(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

aggregate():MetricAggregate {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MetricAggregate.Last;
}

timestampUnixMs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startMetricSample(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addSubsystem(builder:flatbuffers.Builder, subsystemOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, subsystemOffset, 0);
}

static addGroup(builder:flatbuffers.Builder, groupOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, groupOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static addUnit(builder:flatbuffers.Builder, unitOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, unitOffset, 0);
}

static addAggregate(builder:flatbuffers.Builder, aggregate:MetricAggregate) {
  builder.addFieldInt8(4, aggregate, MetricAggregate.Last);
}

static addTimestampUnixMs(builder:flatbuffers.Builder, timestampUnixMs:bigint) {
  builder.addFieldInt64(5, timestampUnixMs, BigInt('0'));
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldFloat64(6, value, 0.0);
}

static endMetricSample(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishMetricSampleBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedMetricSampleBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createMetricSample(builder:flatbuffers.Builder, subsystemOffset:flatbuffers.Offset, groupOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, unitOffset:flatbuffers.Offset, aggregate:MetricAggregate, timestampUnixMs:bigint, value:number):flatbuffers.Offset {
  MetricSample.startMetricSample(builder);
  MetricSample.addSubsystem(builder, subsystemOffset);
  MetricSample.addGroup(builder, groupOffset);
  MetricSample.addName(builder, nameOffset);
  MetricSample.addUnit(builder, unitOffset);
  MetricSample.addAggregate(builder, aggregate);
  MetricSample.addTimestampUnixMs(builder, timestampUnixMs);
  MetricSample.addValue(builder, value);
  return MetricSample.endMetricSample(builder);
}
}
