// automatically generated by the FlatBuffers compiler, do not modify

package com.soonerrobotics.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ImageFrame extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ImageFrame getRootAsImageFrame(ByteBuffer _bb) { return getRootAsImageFrame(_bb, new ImageFrame()); }
  public static ImageFrame getRootAsImageFrame(ByteBuffer _bb, ImageFrame obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ImageFrame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long timestamp() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long sequenceNumber() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long width() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long height() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String encoding() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer encodingAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer encodingInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String identifier() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer identifierAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer identifierInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public int imageData(int j) { int o = __offset(16); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int imageDataLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector imageDataVector() { return imageDataVector(new ByteVector()); }
  public ByteVector imageDataVector(ByteVector obj) { int o = __offset(16); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer imageDataAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer imageDataInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }

  public static int createImageFrame(FlatBufferBuilder builder,
      long timestamp,
      long sequenceNumber,
      long width,
      long height,
      int encodingOffset,
      int identifierOffset,
      int imageDataOffset) {
    builder.startTable(7);
    ImageFrame.addTimestamp(builder, timestamp);
    ImageFrame.addImageData(builder, imageDataOffset);
    ImageFrame.addIdentifier(builder, identifierOffset);
    ImageFrame.addEncoding(builder, encodingOffset);
    ImageFrame.addHeight(builder, height);
    ImageFrame.addWidth(builder, width);
    ImageFrame.addSequenceNumber(builder, sequenceNumber);
    return ImageFrame.endImageFrame(builder);
  }

  public static void startImageFrame(FlatBufferBuilder builder) { builder.startTable(7); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(0, timestamp, 0L); }
  public static void addSequenceNumber(FlatBufferBuilder builder, long sequenceNumber) { builder.addInt(1, (int) sequenceNumber, (int) 0L); }
  public static void addWidth(FlatBufferBuilder builder, long width) { builder.addInt(2, (int) width, (int) 0L); }
  public static void addHeight(FlatBufferBuilder builder, long height) { builder.addInt(3, (int) height, (int) 0L); }
  public static void addEncoding(FlatBufferBuilder builder, int encodingOffset) { builder.addOffset(4, encodingOffset, 0); }
  public static void addIdentifier(FlatBufferBuilder builder, int identifierOffset) { builder.addOffset(5, identifierOffset, 0); }
  public static void addImageData(FlatBufferBuilder builder, int imageDataOffset) { builder.addOffset(6, imageDataOffset, 0); }
  public static int createImageDataVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createImageDataVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startImageDataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endImageFrame(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishImageFrameBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedImageFrameBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ImageFrame get(int j) { return get(new ImageFrame(), j); }
    public ImageFrame get(ImageFrame obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

