// automatically generated by the FlatBuffers compiler, do not modify

package com.soonerrobotics.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Location extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Location __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double latitude() { return bb.getDouble(bb_pos + 0); }
  public double longitude() { return bb.getDouble(bb_pos + 8); }

  public static int createLocation(FlatBufferBuilder builder, double latitude, double longitude) {
    builder.prep(8, 16);
    builder.putDouble(longitude);
    builder.putDouble(latitude);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Location get(int j) { return get(new Location(), j); }
    public Location get(Location obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

