// automatically generated by the FlatBuffers compiler, do not modify

package com.soonerrobotics.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Orientation extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Orientation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float pitch() { return bb.getFloat(bb_pos + 0); }
  public float roll() { return bb.getFloat(bb_pos + 4); }
  public float yaw() { return bb.getFloat(bb_pos + 8); }

  public static int createOrientation(FlatBufferBuilder builder, float pitch, float roll, float yaw) {
    builder.prep(4, 12);
    builder.putFloat(yaw);
    builder.putFloat(roll);
    builder.putFloat(pitch);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Orientation get(int j) { return get(new Orientation(), j); }
    public Orientation get(Orientation obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

