// automatically generated by the FlatBuffers compiler, do not modify

package com.soonerrobotics.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class VectornavReport extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static VectornavReport getRootAsVectornavReport(ByteBuffer _bb) { return getRootAsVectornavReport(_bb, new VectornavReport()); }
  public static VectornavReport getRootAsVectornavReport(ByteBuffer _bb, VectornavReport obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VectornavReport __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long timestamp() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long sequenceNumber() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public com.soonerrobotics.flatbuffers.Location location() { return location(new com.soonerrobotics.flatbuffers.Location()); }
  public com.soonerrobotics.flatbuffers.Location location(com.soonerrobotics.flatbuffers.Location obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.soonerrobotics.flatbuffers.Orientation orientation() { return orientation(new com.soonerrobotics.flatbuffers.Orientation()); }
  public com.soonerrobotics.flatbuffers.Orientation orientation(com.soonerrobotics.flatbuffers.Orientation obj) { int o = __offset(10); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public int numSatellites() { int o = __offset(12); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public byte fixQuality() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static void startVectornavReport(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(0, timestamp, 0L); }
  public static void addSequenceNumber(FlatBufferBuilder builder, long sequenceNumber) { builder.addInt(1, (int) sequenceNumber, (int) 0L); }
  public static void addLocation(FlatBufferBuilder builder, int locationOffset) { builder.addStruct(2, locationOffset, 0); }
  public static void addOrientation(FlatBufferBuilder builder, int orientationOffset) { builder.addStruct(3, orientationOffset, 0); }
  public static void addNumSatellites(FlatBufferBuilder builder, int numSatellites) { builder.addShort(4, (short) numSatellites, (short) 0); }
  public static void addFixQuality(FlatBufferBuilder builder, byte fixQuality) { builder.addByte(5, fixQuality, 0); }
  public static int endVectornavReport(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishVectornavReportBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedVectornavReportBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VectornavReport get(int j) { return get(new VectornavReport(), j); }
    public VectornavReport get(VectornavReport obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

