// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ARCLOGCPP_IGVC_ARC_H_
#define FLATBUFFERS_GENERATED_ARCLOGCPP_IGVC_ARC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace igvc {
namespace arc {

struct ArcLog;
struct ArcLogBuilder;

struct ArcLog FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ArcLogBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_SEQUENCE_NUMBER = 6,
    VT_METHOD_CALLER = 8,
    VT_LOG_LEVEL = 10,
    VT_MESSAGE = 12
  };
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint32_t sequence_number() const {
    return GetField<uint32_t>(VT_SEQUENCE_NUMBER, 0);
  }
  const ::flatbuffers::String *method_caller() const {
    return GetPointer<const ::flatbuffers::String *>(VT_METHOD_CALLER);
  }
  const ::flatbuffers::String *log_level() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LOG_LEVEL);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint32_t>(verifier, VT_SEQUENCE_NUMBER, 4) &&
           VerifyOffset(verifier, VT_METHOD_CALLER) &&
           verifier.VerifyString(method_caller()) &&
           VerifyOffset(verifier, VT_LOG_LEVEL) &&
           verifier.VerifyString(log_level()) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
};

struct ArcLogBuilder {
  typedef ArcLog Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(ArcLog::VT_TIMESTAMP, timestamp, 0);
  }
  void add_sequence_number(uint32_t sequence_number) {
    fbb_.AddElement<uint32_t>(ArcLog::VT_SEQUENCE_NUMBER, sequence_number, 0);
  }
  void add_method_caller(::flatbuffers::Offset<::flatbuffers::String> method_caller) {
    fbb_.AddOffset(ArcLog::VT_METHOD_CALLER, method_caller);
  }
  void add_log_level(::flatbuffers::Offset<::flatbuffers::String> log_level) {
    fbb_.AddOffset(ArcLog::VT_LOG_LEVEL, log_level);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(ArcLog::VT_MESSAGE, message);
  }
  explicit ArcLogBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ArcLog> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ArcLog>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ArcLog> CreateArcLog(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    uint32_t sequence_number = 0,
    ::flatbuffers::Offset<::flatbuffers::String> method_caller = 0,
    ::flatbuffers::Offset<::flatbuffers::String> log_level = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  ArcLogBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_message(message);
  builder_.add_log_level(log_level);
  builder_.add_method_caller(method_caller);
  builder_.add_sequence_number(sequence_number);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ArcLog> CreateArcLogDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    uint32_t sequence_number = 0,
    const char *method_caller = nullptr,
    const char *log_level = nullptr,
    const char *message = nullptr) {
  auto method_caller__ = method_caller ? _fbb.CreateString(method_caller) : 0;
  auto log_level__ = log_level ? _fbb.CreateString(log_level) : 0;
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return igvc::arc::CreateArcLog(
      _fbb,
      timestamp,
      sequence_number,
      method_caller__,
      log_level__,
      message__);
}

inline const igvc::arc::ArcLog *GetArcLog(const void *buf) {
  return ::flatbuffers::GetRoot<igvc::arc::ArcLog>(buf);
}

inline const igvc::arc::ArcLog *GetSizePrefixedArcLog(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<igvc::arc::ArcLog>(buf);
}

inline bool VerifyArcLogBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<igvc::arc::ArcLog>(nullptr);
}

inline bool VerifySizePrefixedArcLogBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<igvc::arc::ArcLog>(nullptr);
}

inline void FinishArcLogBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<igvc::arc::ArcLog> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedArcLogBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<igvc::arc::ArcLog> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace arc
}  // namespace igvc

#endif  // FLATBUFFERS_GENERATED_ARCLOGCPP_IGVC_ARC_H_
