// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_IMAGEFRAMECPP_IGVC_H_
#define FLATBUFFERS_GENERATED_IMAGEFRAMECPP_IGVC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace igvc {

struct ImageFrame;
struct ImageFrameBuilder;

struct ImageFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ImageFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_SEQUENCE_NUMBER = 6,
    VT_WIDTH = 8,
    VT_HEIGHT = 10,
    VT_ENCODING = 12,
    VT_IDENTIFIER = 14,
    VT_IMAGE_DATA = 16
  };
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint32_t sequence_number() const {
    return GetField<uint32_t>(VT_SEQUENCE_NUMBER, 0);
  }
  uint32_t width() const {
    return GetField<uint32_t>(VT_WIDTH, 0);
  }
  uint32_t height() const {
    return GetField<uint32_t>(VT_HEIGHT, 0);
  }
  const ::flatbuffers::String *encoding() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ENCODING);
  }
  const ::flatbuffers::String *identifier() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IDENTIFIER);
  }
  const ::flatbuffers::Vector<uint8_t> *image_data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_IMAGE_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint32_t>(verifier, VT_SEQUENCE_NUMBER, 4) &&
           VerifyField<uint32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_HEIGHT, 4) &&
           VerifyOffset(verifier, VT_ENCODING) &&
           verifier.VerifyString(encoding()) &&
           VerifyOffset(verifier, VT_IDENTIFIER) &&
           verifier.VerifyString(identifier()) &&
           VerifyOffset(verifier, VT_IMAGE_DATA) &&
           verifier.VerifyVector(image_data()) &&
           verifier.EndTable();
  }
};

struct ImageFrameBuilder {
  typedef ImageFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(ImageFrame::VT_TIMESTAMP, timestamp, 0);
  }
  void add_sequence_number(uint32_t sequence_number) {
    fbb_.AddElement<uint32_t>(ImageFrame::VT_SEQUENCE_NUMBER, sequence_number, 0);
  }
  void add_width(uint32_t width) {
    fbb_.AddElement<uint32_t>(ImageFrame::VT_WIDTH, width, 0);
  }
  void add_height(uint32_t height) {
    fbb_.AddElement<uint32_t>(ImageFrame::VT_HEIGHT, height, 0);
  }
  void add_encoding(::flatbuffers::Offset<::flatbuffers::String> encoding) {
    fbb_.AddOffset(ImageFrame::VT_ENCODING, encoding);
  }
  void add_identifier(::flatbuffers::Offset<::flatbuffers::String> identifier) {
    fbb_.AddOffset(ImageFrame::VT_IDENTIFIER, identifier);
  }
  void add_image_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> image_data) {
    fbb_.AddOffset(ImageFrame::VT_IMAGE_DATA, image_data);
  }
  explicit ImageFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ImageFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ImageFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ImageFrame> CreateImageFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    uint32_t sequence_number = 0,
    uint32_t width = 0,
    uint32_t height = 0,
    ::flatbuffers::Offset<::flatbuffers::String> encoding = 0,
    ::flatbuffers::Offset<::flatbuffers::String> identifier = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> image_data = 0) {
  ImageFrameBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_image_data(image_data);
  builder_.add_identifier(identifier);
  builder_.add_encoding(encoding);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_sequence_number(sequence_number);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ImageFrame> CreateImageFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    uint32_t sequence_number = 0,
    uint32_t width = 0,
    uint32_t height = 0,
    const char *encoding = nullptr,
    const char *identifier = nullptr,
    const std::vector<uint8_t> *image_data = nullptr) {
  auto encoding__ = encoding ? _fbb.CreateString(encoding) : 0;
  auto identifier__ = identifier ? _fbb.CreateString(identifier) : 0;
  auto image_data__ = image_data ? _fbb.CreateVector<uint8_t>(*image_data) : 0;
  return igvc::CreateImageFrame(
      _fbb,
      timestamp,
      sequence_number,
      width,
      height,
      encoding__,
      identifier__,
      image_data__);
}

inline const igvc::ImageFrame *GetImageFrame(const void *buf) {
  return ::flatbuffers::GetRoot<igvc::ImageFrame>(buf);
}

inline const igvc::ImageFrame *GetSizePrefixedImageFrame(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<igvc::ImageFrame>(buf);
}

inline bool VerifyImageFrameBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<igvc::ImageFrame>(nullptr);
}

inline bool VerifySizePrefixedImageFrameBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<igvc::ImageFrame>(nullptr);
}

inline void FinishImageFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<igvc::ImageFrame> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedImageFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<igvc::ImageFrame> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace igvc

#endif  // FLATBUFFERS_GENERATED_IMAGEFRAMECPP_IGVC_H_
