// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VECTORNAVREPORTCPP_IGVC_H_
#define FLATBUFFERS_GENERATED_VECTORNAVREPORTCPP_IGVC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace igvc {

struct Location;

struct Orientation;

struct VectornavReport;
struct VectornavReportBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Location FLATBUFFERS_FINAL_CLASS {
 private:
  double latitude_;
  double longitude_;

 public:
  Location()
      : latitude_(0),
        longitude_(0) {
  }
  Location(double _latitude, double _longitude)
      : latitude_(::flatbuffers::EndianScalar(_latitude)),
        longitude_(::flatbuffers::EndianScalar(_longitude)) {
  }
  double latitude() const {
    return ::flatbuffers::EndianScalar(latitude_);
  }
  double longitude() const {
    return ::flatbuffers::EndianScalar(longitude_);
  }
};
FLATBUFFERS_STRUCT_END(Location, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Orientation FLATBUFFERS_FINAL_CLASS {
 private:
  float pitch_;
  float roll_;
  float yaw_;

 public:
  Orientation()
      : pitch_(0),
        roll_(0),
        yaw_(0) {
  }
  Orientation(float _pitch, float _roll, float _yaw)
      : pitch_(::flatbuffers::EndianScalar(_pitch)),
        roll_(::flatbuffers::EndianScalar(_roll)),
        yaw_(::flatbuffers::EndianScalar(_yaw)) {
  }
  float pitch() const {
    return ::flatbuffers::EndianScalar(pitch_);
  }
  float roll() const {
    return ::flatbuffers::EndianScalar(roll_);
  }
  float yaw() const {
    return ::flatbuffers::EndianScalar(yaw_);
  }
};
FLATBUFFERS_STRUCT_END(Orientation, 12);

struct VectornavReport FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VectornavReportBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_SEQUENCE_NUMBER = 6,
    VT_LOCATION = 8,
    VT_ORIENTATION = 10,
    VT_NUM_SATELLITES = 12,
    VT_FIX_QUALITY = 14
  };
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint32_t sequence_number() const {
    return GetField<uint32_t>(VT_SEQUENCE_NUMBER, 0);
  }
  const igvc::Location *location() const {
    return GetStruct<const igvc::Location *>(VT_LOCATION);
  }
  const igvc::Orientation *orientation() const {
    return GetStruct<const igvc::Orientation *>(VT_ORIENTATION);
  }
  uint16_t num_satellites() const {
    return GetField<uint16_t>(VT_NUM_SATELLITES, 0);
  }
  int8_t fix_quality() const {
    return GetField<int8_t>(VT_FIX_QUALITY, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint32_t>(verifier, VT_SEQUENCE_NUMBER, 4) &&
           VerifyField<igvc::Location>(verifier, VT_LOCATION, 8) &&
           VerifyField<igvc::Orientation>(verifier, VT_ORIENTATION, 4) &&
           VerifyField<uint16_t>(verifier, VT_NUM_SATELLITES, 2) &&
           VerifyField<int8_t>(verifier, VT_FIX_QUALITY, 1) &&
           verifier.EndTable();
  }
};

struct VectornavReportBuilder {
  typedef VectornavReport Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(VectornavReport::VT_TIMESTAMP, timestamp, 0);
  }
  void add_sequence_number(uint32_t sequence_number) {
    fbb_.AddElement<uint32_t>(VectornavReport::VT_SEQUENCE_NUMBER, sequence_number, 0);
  }
  void add_location(const igvc::Location *location) {
    fbb_.AddStruct(VectornavReport::VT_LOCATION, location);
  }
  void add_orientation(const igvc::Orientation *orientation) {
    fbb_.AddStruct(VectornavReport::VT_ORIENTATION, orientation);
  }
  void add_num_satellites(uint16_t num_satellites) {
    fbb_.AddElement<uint16_t>(VectornavReport::VT_NUM_SATELLITES, num_satellites, 0);
  }
  void add_fix_quality(int8_t fix_quality) {
    fbb_.AddElement<int8_t>(VectornavReport::VT_FIX_QUALITY, fix_quality, 0);
  }
  explicit VectornavReportBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VectornavReport> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VectornavReport>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VectornavReport> CreateVectornavReport(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    uint32_t sequence_number = 0,
    const igvc::Location *location = nullptr,
    const igvc::Orientation *orientation = nullptr,
    uint16_t num_satellites = 0,
    int8_t fix_quality = 0) {
  VectornavReportBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_orientation(orientation);
  builder_.add_location(location);
  builder_.add_sequence_number(sequence_number);
  builder_.add_num_satellites(num_satellites);
  builder_.add_fix_quality(fix_quality);
  return builder_.Finish();
}

inline const igvc::VectornavReport *GetVectornavReport(const void *buf) {
  return ::flatbuffers::GetRoot<igvc::VectornavReport>(buf);
}

inline const igvc::VectornavReport *GetSizePrefixedVectornavReport(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<igvc::VectornavReport>(buf);
}

inline bool VerifyVectornavReportBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<igvc::VectornavReport>(nullptr);
}

inline bool VerifySizePrefixedVectornavReportBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<igvc::VectornavReport>(nullptr);
}

inline void FinishVectornavReportBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<igvc::VectornavReport> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedVectornavReportBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<igvc::VectornavReport> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace igvc

#endif  // FLATBUFFERS_GENERATED_VECTORNAVREPORTCPP_IGVC_H_
